### ISSUE TITLE
Kiri:moto - CNC - Outline operation - Outside only issue

### ISSUE THREAD

**Issue by Type8** [GridSpace/grid-apps#103]
Hi,
I am trying to use the 'outside only' flag in the outline operation.
This option seems to be ignore by the cam, he would mill also the inner holes.
The issue is present in both 2.4 and 2.5 versions.

Thanks, Umberto.

![screenshot](https://user-images.githubusercontent.com/3313295/103205546-11a54600-48fa-11eb-8198-845b6961a0c6.png)

**Comment by stewartoallen** [comment]
any hole that goes all the way through the part is considered "outside" the part.

**Comment by Type8** [comment]
Makes sense.
Thanks for the explanation :+1:

**Comment by stewartoallen** [comment]
I will add an option to 2.5 that allows you to omit thru holes when outside only checked
