### ISSUE TITLE
roughing trims off side of object

### ISSUE THREAD

**Issue by foxharp** [GridSpace/grid-apps#105]
Roughing (in 2.5 -- don't know if it's new behavior) seems a little aggressive on the sides of my part.

![2020-12-28_12-45](https://user-images.githubusercontent.com/4249842/103233352-f0008a80-490a-11eb-90ef-6542046afebb.png)

My workspace is attached.

Oh.  Hmm.  I can't attach an arbitrary file type?

I'll put it on the web this time, I guess:  [https://www.foxharp.boston.ma.us/tmp/z/aggressive-roughing.km](url)

paul

**Comment by stewartoallen** [comment]
bug. fixing now. thanks.

**Comment by stewartoallen** [comment]
fix pushed to production. in future, you can drop .km files in discord, if that's easier
