### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by ryans1224** [GridSpace/grid-apps#108]
Get this on inital open of kiri:
`Uncaught SyntaxError: Unexpected token '<'`

![image](https://user-images.githubusercontent.com/7398104/108967426-6bff2080-7677-11eb-8ee0-1d6015a9aa96.png)

_Kiri Version: 2.6
Operating System: Ubuntu 20.04
Browser: Chrome_

**Comment by stewartoallen** [comment]
is this repeatable?

**Comment by ryans1224** [comment]
Yep, happens on every page load. And get it on all browsers, heres firefox:

![image](https://user-images.githubusercontent.com/7398104/108979146-44fa1c00-7682-11eb-97a8-1df74a37c953.png)

Not a major issue just thought worth logging

**Comment by stewartoallen** [comment]
good one. it's trying to load a localization module and not getting a proper 404 response from the server.

**Comment by stewartoallen** [comment]
fixed in production
