### ISSUE TITLE
Make print time available as a GCode Macro placeholder

### ISSUE THREAD

**Issue by oliof** [GridSpace/grid-apps#118]
RepRapFirmware does not recognize Kiri:Motos comment about print time, so it can't show the estimated remaining time in the web UI.

One way to solve this would be to add yet another string to match to RepRapFirmware.
Another way to solve this is to expose print time as a GCode Macro placeholder, so RRF users can modify the end gcode to contain a comment that RRF can read.

Example of envisioned syntax:

```
[...]
;TIME {print-time}
[...]
```

This would add the print time (numeric only, without `s` ) in a compatible format to the GCode for those who need it.

**Comment by stewartoallen** [comment]
I've updated the [docs](https://docs.grid.space/projects/kiri-moto/gcode-macros) to reflect that this is a macro substitution already available in the gcode `footer`.  For example, add this to any printer gcode footer:

```
;TIME {time}
```
