### ISSUE TITLE
FR: Alternating wall count

### ISSUE THREAD

**Issue by oliof** [GridSpace/grid-apps#121]
Various slicers support an alternating wall count setting to improve anchoring of infill in the walls. It would be nice if kiri:moto did this as well.

**Comment by stewartoallen** [comment]
you mean alternating between layers or something else? perhaps a picture is in order

**Comment by oliof** [comment]
Yes, alternating between layers.
[!fractional loops](https://3.bp.blogspot.com/-nLkLHWn3Apw/WbSbaDYAGeI/AAAAAAAADcg/2rKYHGHLo-4BrhxrqkWRstjh-n073mAqQCPcBGAYYCw/s1600/Fractional%2BLoops.jpg), source https://www.sublimelayers.com/2017/10/why-i-love-kisslicer-reason-8.html

**Comment by stewartoallen** [comment]
love it. not hard at all to implement.
