### ISSUE TITLE
Spindle speed not set in export (version 2.6 current)

### ISSUE THREAD

**Issue by marciocoragem** [GridSpace/grid-apps#123]
The spindle speed variable is not used in the export.
The files always set the speed has 1000 rpm.
![Screenshot_20210304_093645](https://user-images.githubusercontent.com/23552991/109944039-b44cbd00-7ccd-11eb-8862-5d265f91a7da.png)
![Screenshot_20210304_093753](https://user-images.githubusercontent.com/23552991/109944043-b4e55380-7ccd-11eb-9de0-08997c6713a6.png)

**Comment by stewartoallen** [comment]
requirements:
* device defines a max spindle speed
* device spindle gcode macro is defined

<img width="505" alt="spindle" src="https://user-images.githubusercontent.com/554275/109973890-f1618100-7cc6-11eb-885c-8691140f9606.png">

**Comment by marciocoragem** [comment]
Thanks,

You are correct.
Before i was using a custom profile and everything was set correct, this time i was in a rush and used one of the default profiles, did not notice it was set 1000 rpm max.
