### ISSUE TITLE
mm

### ISSUE THREAD

**Issue by 0xtrzy** [GridSpace/grid-apps#130]
Hello,

I have trouble with tools. I have 3018 and when I setup tools i must use mm or inch? I setup mm for all program but still have tooltip = inch
second trouble is my spindle is bigest. how tell 'make bigest pocket for my tool AND for spindle too' ?

**Comment by stewartoallen** [comment]
you can use metric tools with an imperial workspace and the other way around. the workspace setup just controls how units are displayed.

I believe we addressed your concerns in the Discord chat, so closing this ticket.
