### ISSUE TITLE
discord chat channel

### ISSUE THREAD

**Issue by 0xtrzy** [GridSpace/grid-apps#131]
not working for me.
abandomed?

https://discord.com/channels/688863523207774209/688863523211968535

**Comment by AlbertMN** [comment]
Channel works fine for me, and it's definitely not abandoned :) Here's an invite link (expires in 7 days); https://discord.gg/QeDnJYEw in case it's because you haven't joined yet.

**Comment by stewartoallen** [comment]
yes, it's still active. unless you have an invite or are already a member, you can't open the channel. here is a permanent link to join the server: https://discord.com/invite/suyCCgr
