### ISSUE TITLE
External thin walls are treated like infill

### ISSUE THREAD

**Issue by oliof** [GridSpace/grid-apps#133]
Posting by request: External thin walls are treated like infill and have the wrong speed applied (standard print speed, rather than finish):

![thinwall1](https://user-images.githubusercontent.com/1230627/110520023-427dd480-810e-11eb-8041-da5dc838b749.png)
![thinwall2](https://user-images.githubusercontent.com/1230627/110520025-43166b00-810e-11eb-93ef-1959ecf7ef4d.png)

In practice this will rarely be an issue due to acceleration and jerk limiting max speeds on these, but it should be fixed nonetheless.

**Comment by stewartoallen** [comment]
This is fixed in the experimental thin-fill in the 2.8 development version. Just check experimental under preferences.

**Comment by stewartoallen** [comment]
re-open if this is still an issue. the thin wall code is being completely re-written in the next release.
