### ISSUE TITLE
Documentation bug: {z} and {height} Macros do different things

### ISSUE THREAD

**Issue by oliof** [GridSpace/grid-apps#140]
On the [GCode Macros](https://docs.grid.space/projects/kiri-moto/gcode-macros) page, it is stated:

> {z} or {height} = current z position

I tried using this in gcode footer to move the print head 5mm off the current height without doing the relative/absolute positioning dance with `G90`/`G91`;I  I chose `{height}` and ran a print, without checking the gcode output.

When I returned later to check on the finished print, I found the print head had knocked the printed part aside. The part was undamaged, but my print head mount and part cooling duct had suffered terminal damage ...

I made an experiment and set the following footer gcode

```
M106 S0                  ; turn off filament cooling fan
M104 S0 T{tool}          ; turn off right extruder
M140 S0 T{tool}          ; turn off bed
G0 X-150 Y150 Z{z+5}; move nozzle off the part
G0 X-150 Y150 Z{height+5}; move nozzle off the part
```

and sliced the kiri:moto sample cube. Knowing it's 25mm in height, and is a well-formed input file, we would expect the lines at the end to end up `G0 X-150 Y150 Z30`. The actual output in the gcode file is:

```
; --- shutdown ---
M1076 S0                 ; turn off filament cooling fan
M104 S0 T0          ; turn off right extruder
M140 S0 T0          ; turn off bed
G0 X-150 Y150 Z30; move nozzle off the part
G0 X-150 Y150 Z0.2505; move nozzle off the part
; --- filament used: 2246.99 mm ---
; --- print time: 1324s ---
```
Obviously, the second is what happened on my machine .... so the documentation should be updated to reflect that `{height}` isn't the current z height, but is layer height.

Also, seeing how the expression is evaluated in the second case, I wonder what happens if I have a model that is a fractional height high if I add 5. So I made a test with a simple fractional cube (10.2mm high). Luckily, in the {z+5} case, the result is 15.2. Since I sliced with adaptive layers, I can confirm that `{height}` reports current layer height:

```
[...] 
;; --- layer 34 (0.291 @ 10.2) ---
[...]
; --- shutdown ---
M106 S0                  ; turn off filament cooling fan
M104 S0 T0          ; turn off right extruder
M140 S0 T0          ; turn off bed
G0 X-150 Y150 Z15.2; move nozzle off the part
G0 X-150 Y150 Z0.2915; move nozzle off the part 
; --- filament used: 321.96 mm ---
; --- print time: 165s ---
```
Again, you can see that if you do `{height+5}`, it's evaluated as `current layer height + 0.0005` for some weird reason. I would argue that that's wrong too...

**Comment by stewartoallen** [comment]
the algebraic fail is the result of a string and a number being added. this will be fixed in tonight's release. the documentation bug was just fixed.
