### ISSUE TITLE
it is possible to use it as an API in post or in get?

### ISSUE THREAD

**Issue by kinj14** [GridSpace/grid-apps#142]
Hello,

it is possible to use it as an API in post or in get, to retrieve the printing time, fillament size, ...?

If so, an idea how to do it, because I don't know how to work with this style of library

thank you in advance

**Comment by stewartoallen** [comment]
Have you looked at the various APIs? https://docs.grid.space/projects/kiri-moto/apis

**Comment by enzoFR60** [comment]
@stewartoallen 
Yes I looked but not all.

@AlbertMN
Okay, I'll try to play with it all,
I explain my use,
it's for a 3d printing website, where we load a stl, and I would like to have "filament used (mm)" to estimate the price, print time.

thank you for your answers

**Comment by stewartoallen** [comment]
I think this is what you're looking for: https://grid.space/kiri/engine.html

**Comment by kinj14** [comment]
I saw this, but I have trouble seeing how to turn it into an api

**Comment by stewartoallen** [comment]
if you want to estimate price and print time accurately, you should do it from the gcode that will be used to make the final product.

**Comment by kinj14** [comment]
I know, I use "grid-apps" for this,
The goal is that the customer upload a .stl, .obj and that afterwards we print it but for that I need a price or an estimate

**Comment by kinj14** [comment]
I just have an idea, call the page that retrieve a link by the url, and load and slice the model, which modifies the page with the information

I will try this

**Comment by stewartoallen** [comment]
You should be able to include the engine as a script in your page and do it all within the page.

**Comment by kinj14** [comment]
On a basic web server (example: apache/php) ?
Which file to take?

**Comment by stewartoallen** [comment]
the script goes into the page html. it's not a server-side thing. the example shows this.

**Comment by kinj14** [comment]
yes but i tried using it on my page but it didn't work

**Comment by stewartoallen** [comment]
can you be more specific?

**Comment by stewartoallen** [comment]
I recommend hopping on the Grid.Space Discord server and going to the `#developers` channel
