### ISSUE TITLE
Settings applied in "export" view aren't applied to re-export without changing mode

### ISSUE THREAD

**Issue by oliof** [GridSpace/grid-apps#145]
When I am in "export" mode, I can close the export window, inspect the slice, and change settings like temperature or fan speed. Hitting "export" again, the newly exported file still uses the values that were set when hitting "export" the first time.

I have to go back to "arrange" or "slice" or "preview" mode, before "export" applies the new settings to a newly exported file.

I would expect that changes that don't need changes to the path planning, like temperature and fan changes, would be applied directly. Not sure what the best way forward is for changes that change the path planning ...

**Comment by stewartoallen** [comment]
hitting export multiple times does just used the cached export. one reason for this is that the settings on the right do not clearly delineate what applies in each of the modes: slice, preview, export. in fact, preview does nothing if you select it in preview mode for this very reason. way back Kiri tried to be smarter about caching various stages and only doing incremental work. this got complex and stood in the way of making improvements.
