### ISSUE TITLE
Depth First not working

### ISSUE THREAD

**Issue by Harvie** [GridSpace/grid-apps#15]
I tried both. latest git and version on https://grid.space/kiri?sm:CAM
None of these has "Depth First" feature working. It just does layer by layer all pockets at the same time.

**Comment by stewartoallen** [comment]
i may have disabled it. there was a report some time back about that failing in some models and i haven't had a chance to track it down and fix it.

**Comment by Harvie** [comment]
[chaos-cam.stl.zip](https://github.com/GridSpace/grid-apps/files/1754251/chaos-cam.stl.zip)

You see that both holes are milled at the same time (even with outside profile):

![image](https://user-images.githubusercontent.com/276504/36629180-b33df85c-1952-11e8-98cd-5ad90745b304.png)

I am not sure if there is better way to snapshot settings to json or something, but i've only managed to do screenshot.

![image](https://user-images.githubusercontent.com/276504/36629143-438bc19c-1952-11e8-9f21-d25213f30de8.png)

**Comment by Harvie** [comment]
BTW what will happen if there's pocket which contains two smaller pockets? Will these get milled "depth first" also? Or are they just treated as one big pocket? (It's not the case with my STL, but i have other one like that...)

For example in this part i have two big separate pockets, but there's small interconnecting channel between them in topmost layers. So i wonder if this will ruin the depth first functionality:

![image](https://user-images.githubusercontent.com/276504/36629251-b6ae4770-1953-11e8-9f36-d65fe45d4f50.png)

**Comment by stewartoallen** [comment]
first, you will only see the computation for depth first in "preview" mode (part will turn blue).  in slice mode, you only see the computed slices.

https://youtu.be/AS0muBsHEdg

as for pocket that merge, it will start with the entire top pocket and when it reaches the bottom of the smaller choke point or (in roughing mode) concentric rings close, it will proceed down the pocket it is in then come back up to complete the other.

**Comment by Harvie** [comment]
Thank you, it suddenly works for me. I wasn't able to get g-code preview in preview mode. I was only seeing opaque model without any paths. I was probably doing someting wrong, but i don't know what it was.

Anyway i figured it out by simulating code in this simulator: http://www.cncwebtools.com/Apps/GCode_Simulator/index.html

And later i even dared to try the Blender Suzanne g-code in foam and i was surprised by the toolpath efficiency. But the foam is not really good for smooth surface finish.

![image](https://user-images.githubusercontent.com/276504/36633329-eb1458fc-1993-11e8-8ca9-ca01ad4cabeb.png)

I really like that Kiri:Moto is so simple to use, but still produces efficient and precise g-code.
