### ISSUE TITLE
Different paths in "slice", compared to "preview"/"export" (possibly thin lines related)

### ISSUE THREAD

**Issue by oliof** [GridSpace/grid-apps#152]
In the attached workspace I get thin lines in the "slice" view of an object, but they do not turn up in "preview" or "export".
This is obviously unexpected and undesired.

[thin_not_in_export.zip](https://github.com/GridSpace/grid-apps/files/6222002/thin_not_in_export.zip)

**Comment by oliof** [comment]
Compare the following images which were sliced with no difference in settings:

![slice-with-thin](https://user-images.githubusercontent.com/1230627/112844293-d99dd280-90a3-11eb-9bf0-b8be40da1a69.jpg)
![export-without-thin](https://user-images.githubusercontent.com/1230627/112844298-db679600-90a3-11eb-8bd7-9ca6ee257d7b.jpg)

The first one is what I'd expect, the second isn't.

**Comment by stewartoallen** [comment]
I see the confusion. The engine has identified that area as a gap (red), but has not filled it. The red is not an extrusion line. It's a debugging line. I added it when debugging the experimental thin-fill, which you have enabled here.

<img width="487" alt="Screen Shot 2021-03-30 at 10 15 28 AM" src="https://user-images.githubusercontent.com/554275/113003622-e6bccf00-9140-11eb-9787-66f5b721a1bb.png">

**Comment by stewartoallen** [comment]
I'm going to close this because it's not really a bug or a feature request. I do have on my todo list to resolve the multiple versions of thin-wall or just add a selector for it.
