### ISSUE TITLE
Objects Sliced in Air

### ISSUE THREAD

**Issue by Waldkaeuzchen** [GridSpace/grid-apps#160]
Hello,
I have got that problem that multiple Parts are shifted into the Air after the slicing-Progess, making the resulting G-Code useless.

Preview:
<img width="775" alt="Pre Slice" src="https://user-images.githubusercontent.com/37881252/116886981-09537380-ac2a-11eb-950d-038914f921d2.PNG">

Result after Slicing:
<img width="772" alt="Export Slice" src="https://user-images.githubusercontent.com/37881252/116887049-1f613400-ac2a-11eb-9bd9-09ca3976670e.PNG">

Single Part Sliced:
<img width="589" alt="expected result" src="https://user-images.githubusercontent.com/37881252/116887101-3142d700-ac2a-11eb-860f-aa533f20f53d.PNG">

G-Code and Profile:
[Files.zip](https://github.com/GridSpace/grid-apps/files/6415329/Files.zip)

**Comment by stewartoallen** [comment]
This has been fixed in 2.9 -- use the top-right person/gear icon to switch versions

**Comment by Waldkaeuzchen** [comment]
Oh, thank you.
