### ISSUE TITLE
outline operator not doing anything 

### ISSUE THREAD

**Issue by geobruce** [GridSpace/grid-apps#164]
I tested this in version 2.8 up to 3.0 dev.
![image](https://user-images.githubusercontent.com/4906120/118126094-1de8f600-b3f8-11eb-85e1-73fcda358a05.png)
![image](https://user-images.githubusercontent.com/4906120/118126163-39ec9780-b3f8-11eb-8ce0-0e5d0ff0a5e6.png)

Am I doing something wrong?

[outline opperation broken.zip](https://github.com/GridSpace/grid-apps/files/6472438/outline.opperation.broken.zip)

**Comment by stewartoallen** [comment]
a bunch of check boxes are missing from your outline operation. and I'm trying to figure out how it got that way.

<img width="135" alt="Screen Shot 2021-05-13 at 9 22 42 AM" src="https://user-images.githubusercontent.com/554275/118132105-51faf180-b3cd-11eb-8e18-768dc6ded737.png">

**Comment by stewartoallen** [comment]
open up your javascript console and paste in these two lines to fix it:

```
kiri.api.conf.get().process.ops[0].inside = false
kiri.api.conf.get().process.ops[0].outside = false
```

**Comment by stewartoallen** [comment]
if you can re-create the steps to get back into this state, please document them so I can fix it.

**Comment by geobruce** [comment]
this doesn't seem to fix it
![image](https://user-images.githubusercontent.com/4906120/118356711-e3f22e00-b576-11eb-8131-dbf31f3de08d.png)
Still the same check boxes

**Comment by stewartoallen** [comment]
if you open Kiri:Moto in an incognito window, does the outline operation show all the checkboxes as pictured above?

**Comment by geobruce** [comment]
Only 4 of the 5 shown in ver: 3.0 Dev 
![image](https://user-images.githubusercontent.com/4906120/118371348-837de380-b5ac-11eb-9a00-90e14bdd6123.png)

**Comment by stewartoallen** [comment]
uncheck `outside only` ... the list is adaptive and hides mutually exclusive options. you can't, for example, choose both `inside only` and `outside only`

**Comment by geobruce** [comment]
oops that way it does work in incognito maybe I should just clear cache, cookies, etc..

**Comment by stewartoallen** [comment]
i'm really not clear on how your outline op got into that state. i need a repeatable set of steps. the commands I gave you should have cleared up any mutually exclusive settings *if* the only operation in your chain was the `outline` op.

**Comment by stewartoallen** [comment]
if this is still an issue, please export your workspace (right click export) and zip it so you can attach it into this report.
