### ISSUE TITLE
leveling cnc

### ISSUE THREAD

**Issue by zerotrzy** [GridSpace/grid-apps#175]
Why leveling is on whole space? why not only over the object?
In my opinion add a checker [x] only over object
leveling over empty space is not necessary

![Przechwycenie obrazu ekranu_2021-07-01_10-24-10](https://user-images.githubusercontent.com/70634364/124091966-a843f280-da56-11eb-9c6a-7122f759513a.png)

**Comment by stewartoallen** [comment]
`clear top` under the roughing operation does what you want. the level op is designed to create a flat surface over the entire stock.

<img width="150" alt="Screen Shot 2021-07-01 at 12 49 26 PM" src="https://user-images.githubusercontent.com/554275/124160940-cd426080-da6a-11eb-8697-7a30ef933b9e.png">

**Comment by ojej** [comment]
flat surface not working if my flute is small, I get shape not flat area
