### ISSUE TITLE
tabs remove?

### ISSUE THREAD

**Issue by zerotrzy** [GridSpace/grid-apps#177]
when i delete tabs:
meybe improve communicat, clear ALL tabs on scene?

**Comment by stewartoallen** [comment]
clicking a tab toggles it on/off. that's how you delete *one* tab. click the trash can to delete all tabs

<img width="191" alt="Screen Shot 2021-07-01 at 12 48 18 PM" src="https://user-images.githubusercontent.com/554275/124160847-af74fb80-da6a-11eb-89a0-7d7634b5d52e.png">

**Comment by ojej** [comment]
i undestand what happened but 'description' is not cleary
