### ISSUE TITLE
STEP upload to CAM fails silently

### ISSUE THREAD

**Issue by globalcitizen** [GridSpace/grid-apps#183]
Thought this would be an interesting project to check out (was half-planning to write my own for a 3+1 axis mill) however when uploading a STEP file I get no model appearing and no debug output.

Went to discord but no text channels.

At the project level it should pay dividends to get people over the initial hump and build community, one might therefore suggest prioritising this category of onboarding issue.

**Comment by stewartoallen** [comment]
there are over a dozen grid.space text channels. where did you go on discord? https://discord.com/invite/suyCCgr
