### ISSUE TITLE
[Feature request](CNC) Waterline toolpath

### ISSUE THREAD

**Issue by geobruce** [GridSpace/grid-apps#185]
Hey
I'm looking for a way to have a waterline like finish more efficient. Kind like the finish in the picture.
![image](https://user-images.githubusercontent.com/4906120/129101093-48c4ca23-b503-42f6-ac70-b8cfdce90a75.png).
More specific in the red circle 
![image](https://user-images.githubusercontent.com/4906120/129101277-55002f1f-8f1a-4638-8a7a-c9690def86dd.png)
I know I can get this by doing a rough operation. But I'd like to make a real big landscape and with a water line resolution (step down) of lets say 1mm. But to clear all the unneeded material 1mm would be way to slow. I could easily clean this up with a 6mm step down.

So what I'm looking for is a workflow that looks like this:

1. Rough away all unneeded material with a step down of 6mm, (leave stock 1mm)
2. Do a waterline operation with a step down of 1mm which just passes the only material that's left. and not all the empty space again. (this is kind of "rest machining" related" but maybe it can be done easier by adapting the rough operation to a waterline operation. (if there is no toolpath under this toolpath perform the toolpath, If this is not the lowest toolpath Z-wise skip this one.)

Thanks in advance!

**Comment by stewartoallen** [comment]
This is what the `outline` operation is for. Use `leave stock` in the `rough` operation then `outline` is the final pass.

**Comment by geobruce** [comment]
thanks!

**Comment by geobruce** [comment]
Hello Allen

Today I had finally time to test this.

But with inside only I only get this:
![image](https://user-images.githubusercontent.com/4906120/130090515-3702f416-ee8b-4b4e-88d3-90537cd2e777.png)
![image](https://user-images.githubusercontent.com/4906120/130090611-7f73105c-6b2d-439f-90a8-845d9862b3b6.png)

When I disable inside only I get this:
![image](https://user-images.githubusercontent.com/4906120/130090879-53c1302c-026e-435f-8ec1-56eb971d5912.png)
![image](https://user-images.githubusercontent.com/4906120/130090801-d4126e4d-fadd-430c-9b80-d3002458d7c8.png)
Here is the workspace if you'd like to try it for your self: [workspace.zip](https://github.com/GridSpace/grid-apps/files/7015293/workspace.zip)

**Comment by stewartoallen** [comment]
usually terrain like this would be `contour` operation

**Comment by geobruce** [comment]
We tried a few different finishes on a small landscape but we'd prefer to have it with a waterline finish.
In the end we'd like to make a rather big landscape 1m x 2m. For our end product we would like for example a "rough" finish operation with step down 3mm. But as we don't want to clear all unneeded material with 3mm step down we would like to clear it with a step down of 8mm and then only clear the material that is left with a step down of 3mm. 

just to illustrate our experiments:
![image](https://user-images.githubusercontent.com/4906120/130316532-5654e728-8f19-4ce7-ac17-8fc1098c0442.png)
![image](https://user-images.githubusercontent.com/4906120/130316536-bd98401c-2f50-45a2-8347-76dac339b324.png)

**Comment by stewartoallen** [comment]
I think using the `clip to` option on stock may allow you to do what you want with outlining. should solve the red circle annotation from your earlier post.

<img width="189" alt="Screen Shot 2021-08-22 at 9 39 29 PM" src="https://user-images.githubusercontent.com/554275/130378657-29210881-5a74-4720-8657-552b226591bc.png">

**Comment by geobruce** [comment]
> I think using the `clip to` option on stock may allow you to do what you want with outlining. should solve the red circle annotation from your earlier post.
> 
> <img alt="Screen Shot 2021-08-22 at 9 39 29 PM" width="189" src="https://user-images.githubusercontent.com/554275/130378657-29210881-5a74-4720-8657-552b226591bc.png">

Thanks I tested this and it works!

**Comment by geobruce** [comment]
> usually terrain like this would be `contour` operation

We tested a few strategies and we really like do the look of the rough operation.
Two problems with this:

1. If there is no option for **rest machining** this will be incredibly in efficient.
2. With clear faces enabled in rough, it slows the pocketing down with a whole layer on that height that will be surfaced instead of just the face.

![image](https://user-images.githubusercontent.com/4906120/130440857-bc9cd8c7-56e8-4429-9c34-a004a242b680.png)


![IMG_20210823_073917](https://user-images.githubusercontent.com/4906120/130440355-81fb52a3-8d66-4c62-8ebe-74d6bebfad82.jpg)

![IMG_20210823_073920](https://user-images.githubusercontent.com/4906120/130440358-5cdc7b7e-b57a-462e-a737-9539efe74fe2.jpg)


![IMG_20210823_073851](https://user-images.githubusercontent.com/4906120/130440345-501f9b1c-2820-4cca-b101-f7ef67664365.jpg)
![IMG_20210823_073854](https://user-images.githubusercontent.com/4906120/130440349-06222f5a-b847-4f04-a2f4-72877e46894c.jpg)
![IMG_20210823_073900](https://user-images.githubusercontent.com/4906120/130440352-f5383869-7837-4cd8-9295-168c7b5e17de.jpg)
![IMG_20210823_073905](https://user-images.githubusercontent.com/4906120/130440353-8dbeec92-2897-4e77-be71-30c3aad01a4b.jpg)
![IMG_20210823_073914](https://user-images.githubusercontent.com/4906120/130440354-4e5591ba-f272-4ed1-8c4c-038509bfdcec.jpg)

**Comment by stewartoallen** [comment]
This is what I would do in 3.4+ -- it's outline clipped to stock

[outline-clip-to-stock.kmz.zip](https://github.com/GridSpace/grid-apps/files/9742519/outline-clip-to-stock.kmz.zip)

<img width="1139" alt="Screen Shot 2022-10-09 at 4 29 11 PM" src="https://user-images.githubusercontent.com/554275/194778137-d80748ed-3be8-4d3b-9d73-a10d16175952.png">
