### ISSUE TITLE
im not able to run the project

### ISSUE THREAD

**Issue by maher610** [GridSpace/grid-apps#187]
i followed all the read me steps and when i open local host im getting "cannot get /kiri" can anyone please help im still new to Node.js

**Comment by stewartoallen** [comment]
Are you on Windows?

**Comment by maher610** [comment]
yes

**Comment by stewartoallen** [comment]
what about this part of the readme ...

**Windows Developers**
this git repo requires symbolic link support. on Windows, this means you have to clone the repo in a command shell with Administrator privileges.

**Comment by maher610** [comment]
i tried opening windows powershell as an administrator and followed the steps but i get the same error

**Comment by stewartoallen** [comment]
have you tried WSL? this issue only exists on Windows. there are others using Windows as their primary platform, so perhaps ask around on the forum or Discord server.

**Comment by maher610** [comment]
i will try that now, Thanks for helping
