### ISSUE TITLE
Add way to position object to the bottom of the stock

### ISSUE THREAD

**Issue by Harvie** [GridSpace/grid-apps#19]
Right now if i place object into stock that is taller than the object it does not get cut out properly, because it's placed into the top of stock material (fig. **A**). This can be desirable in many use cases. But sometimes it might be desirable to put it all the way down to the bottom of stock (fig. **B**), so it can be properly cut out and left hanging only on cutout tabs. That effectively means to rough away any excess stock material above the milled shape. This is especialy usefull, when you don't have stock of thickness suitable for your job.

![image](https://user-images.githubusercontent.com/276504/36633777-8196c420-199b-11e8-8ec0-319ff374da35.png)

**Comment by stewartoallen** [comment]
use "z top offset"

<img width="125" alt="screen shot 2018-02-24 at 2 28 40 pm" src="https://user-images.githubusercontent.com/554275/36634212-0e8d0af6-196f-11e8-9049-afa5a9af2ba3.png">

**Comment by Harvie** [comment]
Sorry, my bad :) It works perfect. Even "z bottom" feature is very usefull.

**Comment by Harvie** [comment]
But i've just realized that this is not very handy when handling complex shapes. If i want to mill 20mm cube from 40mm stock, i can simply set "z top offset" to 20mm and have that compensated. But if i download random STL from thingiverse (let's say model of human body) and want to mill it i have to use some external program to get exact size of model and subtract that from stock height to calculate "z top offset".

So i guess that some checkbox which will switch between positioning at the top and at the bottom of stock would make sense.

**Comment by stewartoallen** [comment]
if you click on the model (turns green), the exact dimension are displayed on the blue bar at the bottom center of the screen.

**Comment by Harvie** [comment]
You never stop amazing me :-D
