### ISSUE TITLE
Toolpath bug V3.0 and 3.1

### ISSUE THREAD

**Issue by geobruce** [GridSpace/grid-apps#191]
![image](https://user-images.githubusercontent.com/4906120/144423560-cf4285b8-243b-4667-8081-e1e341d3e21d.png)
This bug is apparent in v3.0 and 3.1
[rough bug workspace.zip](https://github.com/GridSpace/grid-apps/files/7641893/rough.bug.workspace.zip)

I didn't test older versions.

**Comment by stewartoallen** [comment]
it does a little better than 2.9 -- but I noticed some mesh defects .. the new "heal" operation does an integrity check and noticed gaps. and I found these tags on the model

<img width="506" alt="Screen Shot 2021-12-02 at 5 15 20 PM" src="https://user-images.githubusercontent.com/554275/144512096-b869f286-13a7-47c8-8d69-5b2bb48a5429.png">

<img width="668" alt="Screen Shot 2021-12-02 at 5 15 27 PM" src="https://user-images.githubusercontent.com/554275/144512107-8d91a290-0e38-4ec0-a530-2aaed0f08a06.png">

**Comment by geobruce** [comment]
Is the heal test also able to fix this problem?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stewartoallen** [comment]
unfortunately, no. I haven't gotten eyes on it yet. it could be minute. all I know is that there are open edges somewhere. they could be holes or overlapping faces, or both.

**Comment by stewartoallen** [comment]
the defects in the model line up with the tabs pictured above. it's a series of overlapping and open faces that are very close to the faces of these recesses in the model. this confuses the slicer where the defective faces intersect the model.

<img width="1263" alt="Screen Shot 2021-12-02 at 6 20 07 PM" src="https://user-images.githubusercontent.com/554275/144518451-e6b8e37e-9e09-4875-8390-cf066a910510.png">

**Comment by stewartoallen** [comment]
I imported the STL into Onshape and it reports the same detached bodies. I would like to verify the toolpaths on a clean model. Are you able to produce one?

**Comment by stewartoallen** [comment]
I'm closing this as a non-manifold / fuzzed model issue.
