### ISSUE TITLE
CLI not working

### ISSUE THREAD

**Issue by Lenergyy** [GridSpace/grid-apps#192]
I am trying to use the CLI to automate the some CNC toolpath generation.
I used [this ](https://gitmemory.cn/repo/GridSpace/grid-apps/issues/179) thread as a guid.
But when i try to replicate it, I just get a bunch of errors:

![ERRORS](https://user-images.githubusercontent.com/97316670/148611336-45dfbb76-18ed-4bc5-b3c5-c10e0d76845b.PNG)

I am using the latest versions of node and npm.
It would be very nice if someone would take the time to help me troubleshoot the problem.

**Comment by stewartoallen** [comment]
try the 3.0 branch for stability. I'm making a ton of internal changes in 3.1 that likely caused this. the fix should be easy, though.

**Comment by stewartoallen** [comment]
it's great to have this memorialized in the issue tracker so I don't forget to patch it up before 3.1 final. but it you want real-time help, hope on over to the Discord server or the forum. Both linked from the bottom of the grid.space home page.
