### ISSUE TITLE
[Feature] SLA Resin Volume

### ISSUE THREAD

**Issue by 503Dev** [GridSpace/grid-apps#198]
Hello,

I am working with the latest version of Kiri:Moto on a local dev server.  I noticed SLA operations do not return the volume of estimated resin usage. 

Is there presently any method to obtain this programmatically from the slicing functionality?

**Comment by stewartoallen** [comment]
added volume to export in this commit: https://github.com/GridSpace/grid-apps/commit/0b19a6c98f4c575fbe6759427311eca112e73c61

**Comment by 503Dev** [comment]
Thank you, you are a legend and this project is a godsend for the 3d printing community.

**Comment by 503Dev** [comment]
@stewartoallen Just a question (sorry to nag at your time):

What is the unit being returned? I applied the changes and sliced the test cube and it returns a value of 7200 which is now what I am normally used to seeing.  I might just be missing something, thanks again!

**Comment by stewartoallen** [comment]
It should be cubic millimeters. what would you expect?

**Comment by 503Dev** [comment]
Sorry I am ridiculous, I have been working with other resin slicers and they always display ML which is what I was thinking, cubic mm is obviously what should be expected problematically.  My mind is in the code gutter.  Thank you again.

**Comment by stewartoallen** [comment]
happy to make that conversion (just 1/1000) since you're the only one asking :)

**Comment by 503Dev** [comment]
:) thank you.  Seriously, I am indeed thankful for your awesome work and contributions.
