### ISSUE TITLE
after manual layout, adding a new object reverts to auto-layout; should keep manual layout

### ISSUE THREAD

**Issue by tschundler** [GridSpace/grid-apps#202]
Unfortunately, without #49, it's necessary to layout manually in Kiri:moto. But if I have a layout and want to add something since I have space, it resets the layout.

If layout is manually adjusted, it should set a "dirty" bit for the layout. If that bit is cleared, when a new object, it should not move the existing ones. The flag gets reset by clicking the autolayout option or clearing all objects.

**Comment by stewartoallen** [comment]
Layout will only happen when objects are added if `auto layout` is enabled.
<img width="106" alt="Screen Shot 2022-03-29 at 10 53 03 AM" src="https://user-images.githubusercontent.com/554275/160640471-541eada4-8323-4f29-a1a9-91edace92c04.png">

**Comment by tschundler** [comment]
Thanks, that solves my problem.

I still think automatically switching would still be the best UX, but feel free to close this if you think that feature request isn't practical.

**Comment by stewartoallen** [comment]
great. I will close this for now.
