### ISSUE TITLE
error on "Pocket" -- TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by tschundler** [GridSpace/grid-apps#206]
Workspace:
[workspace.kmz.zip](https://github.com/GridSpace/grid-apps/files/8840423/workspace.kmz.zip)

Open WS in incognito, go to preview, get type error

**Comment by stewartoallen** [comment]
part of another commit made it in with this one :/ oops

**Comment by tschundler** [comment]
thank you
