### ISSUE TITLE
Doubled extrusion

### ISSUE THREAD

**Issue by p3d-dev** [GridSpace/grid-apps#209]
Hello again and sorry,

another issue can be seen with [3d benchy](https://www.thingiverse.com/thing:763622). Slicing with 0.19mm, there is a double extrusion visible on e.g. layer 186.
![AAD79CB2-A4FE-46CB-A013-59759D470555](https://user-images.githubusercontent.com/105526632/173356918-5f8b1be3-767f-4f23-813e-a30c11214a3a.jpeg)

The red marked area indicates this phenomenon. I could not figure out, how to show the print head movement, which would make this double extrusion more obvious.

**Comment by stewartoallen** [comment]
try enabling various thin wall algorithms under the layer menu to see if this helps

**Comment by p3d-dev** [comment]
Thanks for the proposal. I will try this.
