### ISSUE TITLE
Can't drill holes that are just slightly bigger than tool diameter

### ISSUE THREAD

**Issue by Harvie** [GridSpace/grid-apps#21]
I am using 1/8'' (3.175mm) endmill tool. I've made this model (image) with holes of following diameters:
3 mm, 3.175 mm, 3.2 mm and 4 mm. Only the 4mm one is milled by roughing and waterline processes.

I expected that 3.175 or at least 3.2mm and bigger holes will be drilled. But nothing happend.
I also tried to enable "drilling" process, but it didn't changed anything. I've tried to look it up in documentation and even source code, but i still can't figure how to make use of this drilling feature.

![image](https://user-images.githubusercontent.com/276504/36878308-a2ea0bec-1dbe-11e8-8427-853474aede03.png)

**Comment by stewartoallen** [comment]
please share the model with me.  when drilling is enabled, any hole within 1% of the diameter of the chosen bit should turn into a drilling operation.

**Comment by Harvie** [comment]
Do you use OpenSCAD? I tried with this model:

```
cube([30,30, 10], true);
    cylinder(20,3.175/2,3.175/2);
    translate([5,0,-10]) cylinder(50,3.175/2,3.175/2);
    translate([5,5,-10]) cylinder(20,3/2,3/2);
    translate([0,5,-10]) cylinder(20,3.2/2,3.2/2);
    translate([10,0,-10]) cylinder(20,4/2,4/2);
    
}
```

**Comment by stewartoallen** [comment]
<img width="350" alt="screen shot 2018-03-03 at 8 01 02 pm" src="https://user-images.githubusercontent.com/554275/36940945-a64c7490-1f1d-11e8-8474-97f6053c1bbf.png">

that code produces this

**Comment by Harvie** [comment]
sorry, copypaste technology :-) should be ok now.

**Comment by Harvie** [comment]
Here's the STL, if that's more convenient for you:
[drill_test.stl.zip](https://github.com/GridSpace/grid-apps/files/1885880/drill_test.stl.zip)

**Comment by pjz** [comment]
3.2 < 3.175*1.01 (which is 3.20675).  So 'as designed'.

**Comment by stewartoallen** [comment]
The stl you sent has 4 holes.  I enabled drilling w/ 1/8" endmill and it detected and drilled one of the holes.  See the black vertical line.  That's a drill hole.  Screenshot attached.

![screen shot 2018-04-22 at 4 07 28 pm](https://user-images.githubusercontent.com/554275/39099339-720a4166-4647-11e8-8bb9-ed2c02543c32.png)

**Comment by Harvie** [comment]
@stewartoallen I am sorry, but it does not work for me (on https://grid.space/kiri?sm:CAM )
![image](https://user-images.githubusercontent.com/276504/39101117-6f040e5e-4695-11e8-8992-7079563d51fa.png)

Another thing, that amazes me is that you have the model loaded upside down for some reason (there are 5 holes, but only 4 go all the way to the bottom. You have bottom at the top, so you only see 4 holes). For me it loads properly as modeled.

**Comment by stewartoallen** [comment]
so, interestingly, rotating the model 90 degrees changes which holes are recognized (try it several times).  I also flipped it and got the same results as you.  bizarre.  at least I now have a repeatable test case.  thank you for that.  now I can fix it :)

**Comment by Harvie** [comment]
Before i posted previous comment i also tried flipping it upside down, but it didn't helped. Now i tried to slightly rotate model around Z but still no difference.

May this be related to the fact, that in STL you can't really have round holes? Every "round" hole in STL is just polygonal hole with lots of faces.

**Comment by stewartoallen** [comment]
yes, kiri calculates the "roundness" of polygons to determine if they are circles and what their diameter is.  perhaps this is at the margins of javascripts floating point precision.  i'll perhaps make the tolerance tunable and see if there is another fix.

**Comment by Harvie** [comment]
Calculating of roundness sounds like interesting code and topic.

**Comment by stewartoallen** [comment]
https://github.com/GridSpace/grid-apps/blob/master/js/geo-polygon.js#L790

**Comment by Harvie** [comment]
So you basicaly compare area of polygon to area of what you expect circle to be if inscribed in bounding ~~box~~ square of that polygon?

**Comment by stewartoallen** [comment]
did you read the article in the comment? http://www.ehow.com/how_5138742_calculate-circularity.html

**Comment by Harvie** [comment]
Ah, i missed that link and most importantly i also mistranslated the word perimeter. Now it makes perfect sense. You can't fit more area to perimeter than circle does. That's why baloons and bubbles are round. So that should be quite straightforward and reliable algorithm.

**Comment by stewartoallen** [comment]
are you running from source?  I pushed https://github.com/GridSpace/grid-apps/commit/6be15165ce7b833f63318cad6ecae0e407244b4b which may help.  let me know.

**Comment by Harvie** [comment]
No, i always use https://grid.space/kiri?sm:CAM because i rarely have reason to run local copy.

I've downloaded lastest git code with these results:

![image](https://user-images.githubusercontent.com/276504/39157051-4453a3c6-4759-11e8-9117-d1ba2829d910.png)

Both 3.175mm holes and 3.2mm hole were drilled. 3mm and 4mm holes were not. That's pretty much behaviour that i would expect. :smile: Having this tolerance tunable might certainly be useful.

**Comment by Harvie** [comment]
Maybe there should also be some option to enable autodetection that would set circularity threshold based on tool diameter. Probably bigger circles can be more circular as they might have more polygons. But you can't really tell as this heavily depends on what CAD and it's settings you use.

**Comment by Harvie** [comment]
Aha! Just found out that when the circle is too circular it actually gets rejected. When i try circle with too many segments it does not pass the circularity test. Maybe you should use some big number library for this calculation?

**Comment by stewartoallen** [comment]
thanks for all the testing. a big number library would substantially degrade performance. a practical alternative would be to drop points for segments lengths shorter than _x_ where _x_ is tbd based on testing.

**Comment by Harvie** [comment]
how exactly is float limited in javascript? that might give us some insight in what's going on...

**Comment by stewartoallen** [comment]
I believe this is functioning as expected in the current code. Can you confirm?

**Comment by Harvie** [comment]
4mm hole is still not drilled nor milled with 1/8inch bit

**Comment by stewartoallen** [comment]
and I wouldn't expect it to. the drilling op only does holes that are within a very small tolerance of the chosen bit. if you want to drill out a larger hole with a smaller bit, then roughing or outlining will work. but if you want to control the drilling order, use the new trace operation, select the bottom of the hole and put in an appropriate step-down value.

**Comment by Harvie** [comment]
Well, finaly managed to do it.

![image](https://user-images.githubusercontent.com/276504/110024264-7338c500-7d2e-11eb-8eb5-d3a99bfba55b.png)

had to enable 3 operations: outline, roughing and drilling. it seems that drilling does not take place in all holes unless roughing is enabled as well. this is rather confusing. i still do not fully understand how i persuaded it to do what i needed. almost like there is some weird interlock between operations. is there reason for that?

Also had issues that drilling didn't wanted to drill blind holes, or through holes. i don't really remember. but it was really confusing to figure this out and i had to try like 30 times. But it did worked after all.

Anyway. This ticket has been open for 3 years and holy sh*t. You've done some work. Kiri:Moto looks very different from what i remember back then. Good job!

I also like the fact that it seems to run reasonably well even on my trusty old thinkpad x201. In the past years i've been contributing (mostly CAM features) to bCNC and we struggle a lot to get reasonable performance from g-code preview window. That python is slow AF. We can't even afford to rotate preview of 2D g-code using mouse. That's how slow our canvas currently is. And Kiri:Moto has interactive realtime 3D rotating preview in frickin web browser :-D That really puts bCNC CAM in shame. I guess we will have to step up our game :-)

**Comment by stewartoallen** [comment]
I would like to do a whole-sale revisit of drilling at some point. The current implementation is a legacy of Kiri's early days. I think most if not all of the inter-dependence you remember is gone. There should be no relation or behavioral change between the existence of a roughing op and a drilling op or not.

**Comment by Harvie** [comment]
Thanks!
