### ISSUE TITLE
Bridging

### ISSUE THREAD

**Issue by gin66** [GridSpace/grid-apps#210]
Perhaps stupid question: Is there a setting to enable bridging after switching support off ?

**Comment by stewartoallen** [comment]
bridges are printed regardless of whether supports are turned on or off.

**Comment by gin66** [comment]
If slicing the bridge test (https://www.thingiverse.com/thing:284380/files), I have a hard time to identify the bridge. Looks more like the shell is printed and then normal infill. Here is the first “bridge” layer:
![51FC55D3-44AC-4A7A-95A2-6704D56FECDF](https://user-images.githubusercontent.com/5549373/175122112-8cf83d50-9d56-45f4-85cf-d91cd876deac.jpeg)


BTW, in your notes.md is stated: “ can't drag slider bar on ipad / ios -- touch pad scrolling dodgy”. at least on my m1 ipad pro, Slider bar can be dragged by a weird horizontal two finger pinch at the window bottom (close to the slider bar)

**Comment by stewartoallen** [comment]
The best way to print a bridge like that is to use a range to increase the # of shells on that specific layer. KM does not do that for you automatically.

**Comment by gin66** [comment]
How to use a range to set the # of shells for this layer ? From all the settings I can see on https://grid.space/kiri/?ver:3.4.1, none is indicating that feature.

**Comment by stewartoallen** [comment]
covered in this video https://youtu.be/HfOua7GnyEc

**Comment by gin66** [comment]
Thanks. Very good video
