### ISSUE TITLE
Kiri Moto Laser always at S255 despite 5 % setting

### ISSUE THREAD

**Issue by BKLronin** [GridSpace/grid-apps#211]
Hi guys,

experimenting a lot with KM lately and CAM went well so far. Only problem Iǘe got and can´t find any clue is that the laser power is always set to S255. 5% or 100% different machine different settings. Its Always S255 in Gcode.

This is on Firefox, Manjaro.
EDIT: Same with Chrome and different svgs etc

Ayn hint would be of value. Laser is sitting ready for its first cut :).

**Comment by stewartoallen** [comment]
I'll look into why the power value isn't being converted for `S{value}` properly ... in the meantime, you can hard-code the value in the device gcode macro

<img width="755" alt="Screen Shot 2022-06-25 at 7 07 34 PM" src="https://user-images.githubusercontent.com/554275/175793082-5c320675-6c6b-4b4a-a37a-dede288cc3c4.png">

**Comment by BKLronin** [comment]
Thank you very much. 

I ll try a fixed S value tomorrow.

**Comment by BKLronin** [comment]
As I understand bitmaps or pixel based graphics would be lasered by altering the pwam for different intensieties or does it alter speed or number of times passing a layer?

**Comment by stewartoallen** [comment]
Kiri:Moto does not raster images. Once sliced in laser mode, the depth data is gone.  So that's usually something left to programs like LightBurn.

**Comment by BKLronin** [comment]
Ah thanks,

wasn´t sure if there is some raster mode that is triggered somehow. I had a SVG that contained a rasterized part and that information got missing on importing on most laser tools. 

So the fixed s value per machine setup is totally fine. Tried lightburn and it seems nice but I try tor reduce the nr of prgrams I use. 

BTW: Kiri is really nice, I do recommended it every now and then. (F360 cam replacement)

**Comment by stewartoallen** [comment]
Great to hear. Always looking for feedback and ideas to improve it.
