### ISSUE TITLE
onshape doesnt show assemblies when importing

### ISSUE THREAD

**Issue by psy0rz** [GridSpace/grid-apps#212]
Somehow the assemblies tab is missing? I can only import part studios it seems?

Edwin

**Comment by stewartoallen** [comment]
last I checked, Onshape's API does not provide a way to export assemblies as meshes. as a result, the assembly tab was never enabled when bringing parts into KM.

**Comment by stewartoallen** [comment]
assembly import added in 3.5

**Comment by psy0rz** [comment]
epicccc thanks :D
