### ISSUE TITLE
ou_move_l

### ISSUE THREAD

**Issue by gin66** [GridSpace/grid-apps#213]
some translations specify mm/min and some mm/s. Which one is correct ?

**Comment by stewartoallen** [comment]
the only examples I can find of per minute are cnc operations which specify "workspace units / minute" allowing selection between metric to imperial. all other operations which are metric only are millimeters / second.

**Comment by stewartoallen** [comment]
I see. it's a stale translation issue. I did not look at those files. Thanks for pointing it out. Would you like to submit a PR fix?
