### ISSUE TITLE
Analysis of print object apparently fails in specific cases

### ISSUE THREAD

**Issue by p3d-dev** [GridSpace/grid-apps#224]
The following part (stl-file in the wheel.zip file) fails to be sliced correctly:
<img width="768" alt="Bildschirmfoto 2022-10-15 um 13 30 18" src="https://user-images.githubusercontent.com/105526632/195984176-979bb2ac-e68b-403f-b4e3-22268aa31afc.png">

Here is the slicing result. Just dropped in https://grid.space/kiri/ and let it slice. The line across the result is from the print bounding box. 
<img width="833" alt="Bildschirmfoto 2022-10-15 um 13 30 09" src="https://user-images.githubusercontent.com/105526632/195984178-e6b6a733-a449-4500-8a96-7d58389b689a.png">
[wheel.zip](https://github.com/GridSpace/grid-apps/files/9791914/wheel.zip)

**Comment by stewartoallen** [comment]
this part is non-manifold. it's two parts overlapping in such a way that faces overlap and some vertices are duplicated. this makes it impossible for the slicer to determine inside from outside definitively. I tried fixing it in blender, but blender could not properly boolean it either. the first clue is the seam in pic one. wireframe view shows the overlapping parts clearly.

<img width="621" alt="Screen Shot 2022-10-15 at 10 34 46 AM" src="https://user-images.githubusercontent.com/554275/195992184-a2d75c2d-8c87-420b-a8bf-3d96abc087c7.png">

<img width="940" alt="Screen Shot 2022-10-15 at 10 34 52 AM" src="https://user-images.githubusercontent.com/554275/195992183-705469bc-79c5-4a09-b225-fd096345d49f.png">
