### ISSUE TITLE
Tools with shared number can interfere with simulation

### ISSUE THREAD

**Issue by stewartoallen** [GridSpace/grid-apps#230]
by the time the segment data reaches the animation engine, the internal tool ID is lost because gcode only cares about the tool #.

**Comment by wcraigtrader** [comment]
I had defined both 1/4" tools and 1/8" tools, and I had given each tool a tool # to match their positions in the Carvera tool changer. This meant that I had a 1/4" spiral down cut bit with tool #1 and a 1/8" up cut end mill, each numbered as tool 1. (I actually had 6 numbered tools in each size.)

When animating a toolpath that was defined for the 1/8" end mill, the path was cutting with the 1/4" end mill properties.

Renumbering the 1/4" bits solved this problem, but it means that I'll have to renumber all the conflicting bits every time I switch collets and/or jobs.

**Comment by stewartoallen** [comment]
I will revisit this for 3.9
