### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [GridSpace/grid-apps#234]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by wjsteele** [comment]
Well... considering that the owner pushed a commit 8 hours ago, I'd say it is.  However, with that said, this isn't a general discussion forum... it's for issues/features requests/bug tracking, etc.  See here to learn how to use Issues and Discussions: [https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues )  And don't forget to close this issue so it's not in the list of work to do.

**Comment by stewartoallen** [comment]
https://forum.grid.space/ -- message board style
https://discord.com/invite/suyCCgr -- real time chat

should be linked from the grid.space home page
