### ISSUE TITLE
API Not Working "https://grid.space/kiri/engine.html"

### ISSUE THREAD

**Issue by mahmood265** [GridSpace/grid-apps#239]
Hi! I have checked the link that I have used to learn about it, and it is not working on webpage even I have cleared my cache. I am using edge.
Error: "i.client.unrotate is not a function"
To solve this issue I downloaded the file and run it on my server. I temporary removed it from engine.js file and try again. This time it works up to generating vertices and, stops working slicing forward. I have tried to figure it out but not found.
**Code I have used is same as described in link just changed used my own stl file
![Screenshot (7)](https://user-images.githubusercontent.com/112277371/212474049-eab2c911-18ca-4543-a6cc-030ad7f4fff7.jpg)
:**
```
kiri.newEngine()
    .setListener(display_message)
    .load("/obj/cube.stl")
    .then(eng => eng.setProcess({
        sliceShells: 1,
        sliceFillSparse: 0.25,
        sliceTopLayers: 2,
        sliceBottomLayers: 2
    }))
    .then(eng => eng.setDevice({
        gcodePre: [ "M82", "M104 S220" ],
        gcodePost: [ "M107" ]
    }))
    .then(eng => eng.slice())
    .then(eng => eng.prepare())
    .then(eng => eng.export())
    .then(display_gcode);

```

**Comment by mahmood265** [comment]
![image](https://user-images.githubusercontent.com/112277371/212474201-63f8be21-8101-4f77-bf43-b1e1e7cf3353.png)
Console output after temporary removing unrotate function.
Sorry to put it here it was not uploading in above document.

**Comment by stewartoallen** [comment]
fixed. will be pushed to production shortly.
