### ISSUE TITLE
Support for V-bits, rounded bits and non-centercutting bits

### ISSUE THREAD

**Issue by Harvie** [GridSpace/grid-apps#24]
![image](https://user-images.githubusercontent.com/276504/36941725-781c4b96-1f62-11e8-91b2-7818de1debd2.png)

**V-bits** are quite common and usefull, because they are quite durable and can both remove material in bulk and carve tiny details (up to 0.1 mm). These would be most usefull to add.

**Rounded** bits are similar to ball ends, but radius of the end is smaller than radius of the shaft. They are like hybrid between ball head and plain old square end mill. I kinda like them, because they produce smoother pocket bottoms. Also they are less prone to break, since they don't have sharp corners that make weak spot of most endmills and create leverage that puts whole tool under bigger load.

**Non-centercutting** bits would be harder to add, since they can't plunge too much and therefore require spiral cutting (#17). These are usualy cheap bits made for fast cutting/routing.

**Comment by stewartoallen** [comment]
not on my list, but i'll add it.  computationally more expensive.

**Comment by Harvie** [comment]
Ideal case would be if we could import STL or DXF models of custom milling bits. BlenderCAM does it and it's still years faster than PyCAM, which can't do this. But i guess it's still much more expensive than what you do right now.

**Comment by stewartoallen** [comment]
STL import for custom bit profiles would not be too difficult.

**Comment by stewartoallen** [comment]
ball and taper mills supported.
