### ISSUE TITLE
Local deployment failed

### ISSUE THREAD

**Issue by linhuanfengQ** [GridSpace/grid-apps#258]
After I run this command line, print the following output. Does this mean the startup was successful
gs-app-server
231024.095710 '[appserver]' 'app-server running: ports=[8080] apps=[apps] data=[data] logs=[logs]'

But when I visited the website, 404 appeared

**Comment by stewartoallen** [comment]
windows? if so, you need to re-clone the repo w/ admin privileges so sym links work. if no, don't forget `/kiri` on the url

localhost:8080/kiri

**Comment by linhuanfengQ** [comment]
![26827f369423c6e123c16491649a072](https://github.com/GridSpace/grid-apps/assets/140363834/4d9fe882-3031-4111-a3af-63ab3a8d58b3)

Hello, my deployment on Centos also failed

**Comment by linhuanfengQ** [comment]
Hello, may I ask if it is possible to update the deployment method, such as using NPM build and NPM start to achieve testing and production deployment, instead of using GS app server

**Comment by stewartoallen** [comment]
happy to accept pull requests that address this
