### ISSUE TITLE
Locks up on Preview with no processes

### ISSUE THREAD

**Issue by pjz** [GridSpace/grid-apps#26]
I imported my object then selected it and hit 'preview' ( in 'CNC Milling' mode if it matters ) and then hit an infinitely-repeating "there are no processes" popup.  I had to force-reload the page to break it.

**Comment by stewartoallen** [comment]
what is your operating system and browser? I am unable to reproduce so far. thanks

**Comment by pjz** [comment]
Chrome on Linux.

**Comment by stewartoallen** [comment]
trying with the same setup. are there any CNC processes selected? do you have a privacy mode set that would prevent localStorage from persisting settings?

**Comment by pjz** [comment]
No... I'll see if I can repro again and make better notes.

**Comment by pjz** [comment]
Can't repro.  If I can get better repro steps for you, I'll re-open.
