### ISSUE TITLE
Z limit not respected by Outline, Roughing

### ISSUE THREAD

**Issue by cvandermey** [GridSpace/grid-apps#262]
In my model, I've set the z bottom to 1.5" on a 3" depth model.  Outline/Roughing generate paths and export gcode for this.  Interestingly, contouring does not.  OSX, 13.6, Chrome
<img width="800" alt="Screenshot 2023-11-12 at 5 00 09 PM" src="https://github.com/GridSpace/grid-apps/assets/2042957/1a6c6e16-c845-4757-b4b0-1202006f0c93">
<img width="733" alt="Screenshot 2023-11-13 at 1 34 08 PM" src="https://github.com/GridSpace/grid-apps/assets/2042957/fa751783-51a9-4a19-84bb-79121112b056">

**Comment by stewartoallen** [comment]
there were recent fixed that could have addressed this. if it's not fixed in 3.9.6 and 4.0, please re-open the ticket and attach a workspace `.kmz`
