### ISSUE TITLE
CNC "rough" operation does not retract the tool

### ISSUE THREAD

**Issue by TAR-ALEX** [GridSpace/grid-apps#263]
Description:
CNC "rough" operation does not retract the tool and goes straight through the material in some cases. In my particular case, it actually damages the model it is cutting out.

How to replicate this:
I used version 3.9 at this link: https://grid.space/kiri/
I loaded the following model and switched to the cnc mode:  [magic.stl.zip](https://github.com/GridSpace/grid-apps/files/13455769/magic.stl.zip)
I used the default CNC machine. 
I applied the following rough operation: 
![image](https://github.com/GridSpace/grid-apps/assets/71244213/8ebd42d7-ac75-4618-bf79-0e9552f58cdd)
After animating the model I get the following results (damaged areas circled in red):
![image](https://github.com/GridSpace/grid-apps/assets/71244213/3d4be786-1302-48ea-8cb7-6bf64d8ba4ea)
The movement paths confirm this:
![image](https://github.com/GridSpace/grid-apps/assets/71244213/9a7c3409-b820-45f5-8ccf-2b16fbf2dbb6)

Oddly enough, it works perfectly with a smaller bit and does all of the retractions properly.

**Comment by TAR-ALEX** [comment]
After some more testing, it appears that it works as intended in version 3.8 for the same exact input.

**Comment by stewartoallen** [comment]
Thanks for digging into this and providing an example. I will take a closer look when I return in mid December.

**Comment by stewartoallen** [comment]
this appears to have been fixed by other recent path fixes. please confirm and re-open if you can still duplicate in 3.9.6 or 4.0

**Comment by TAR-ALEX** [comment]
Thank you for the fix! I confirm that the problem has been solved and can no longer replicate the issue.
