### ISSUE TITLE
Add button (or setting, or something else) to duplicate or copy an operation WITH its selected surfaces.

### ISSUE THREAD

**Issue by roboman2444** [GridSpace/grid-apps#273]
Existing behavior is adding another of the same type of operation does duplicate settings, but having to re-select many surfaces gets tedious. A feature to also duplicate selected surfaces would be nice, either a toggleable behavior setting that modifies the current add-op functionality, a button to duplicate an operation fully, or a way to "transfer" selected surfaces from one op to another.

**Comment by stewartoallen** [comment]
shift + clicking an op clones it with all of the selected surfaces or traces. I forgot that this was already implemented when we chatted.
