### ISSUE TITLE
Part anchor appears under part [FDM]

### ISSUE THREAD

**Issue by Adqam64** [GridSpace/grid-apps#278]
When slicing the STLs for a CR-30 belt printer for files from [this Thingiverse link](https://www.thingiverse.com/thing:3095799/files), the anchor appears under the part for some reason.  Verified with at least the 8x8 and smooth files.
![image](https://github.com/GridSpace/grid-apps/assets/95533659/ed584418-9ac1-4334-be42-b4c9d034768e)
![image](https://github.com/GridSpace/grid-apps/assets/95533659/c4c5ef81-4f87-4687-b06d-3c847d1a3839)
![image](https://github.com/GridSpace/grid-apps/assets/95533659/a251f893-29eb-481e-ab72-d133ca7d7d73)

**Comment by stewartoallen** [comment]
organic parts rarely have real flat bottoms. to compensate, set the `flatten` value under `base` to something like `0.5` or `0.75` and report back :) pair that with the `lay flat` option to select a face to place on the bed. but flatten is the more important option on the belt.

**Comment by Adqam64** [comment]
Ah, flatten fixed it.  Thanks!
