### ISSUE TITLE
Shell width / Nozzle size >= 1.0 will generate extra moves.

### ISSUE THREAD

**Issue by Kenzu** [GridSpace/grid-apps#279]
Hi

Pictures tell it all.

![1mm](https://github.com/GridSpace/grid-apps/assets/505634/79d23f16-f432-43bb-baf1-92ccadb6312c)
![099](https://github.com/GridSpace/grid-apps/assets/505634/4ffac03f-5f12-438b-a242-e87b40593afb)

Thanks

Jesper

**Comment by stewartoallen** [comment]
if you don't mind, please email the workspace (.kmz) to [ sa at grid dot space ] - will save me time synthesizing a test case. thanks

**Comment by Kenzu** [comment]
I

I had to put it in a zip file :-)

[workspace.zip](https://github.com/user-attachments/files/15950496/workspace.zip)

**Comment by Kenzu** [comment]
Perfect, will do some testing today.

Thanks a lot

Jesper Lindeberg


man. 24. jun. 2024 kl. 16.44 skrev Stewart Allen ***@***.***>:

**Comment by Kenzu** [comment]
Hi

I did some tests and everything seems to work :-)
I also found some good settings for my channel letters.

So thanks a lot

![fixed](https://github.com/GridSpace/grid-apps/assets/505634/90eb2d2e-650e-4190-9ac3-3307441b52da)
![fixed](https://github.com/GridSpace/grid-apps/assets/505634/90eb2d2e-650e-4190-9ac3-3307441b52da)
