### ISSUE TITLE
Slow Printing Speed

### ISSUE THREAD

**Issue by goldenninja13** [GridSpace/grid-apps#281]
For some reason after this recent update that changed the appearance of the slicer I am getting really slow printer speed. I have tried changing my minimum movement speed but it seems like it is still overriding that value. If I had to guess it prints at about 1/10 of a mm/s. I'm using an ender 3 v2. It wasn't doing this until this update.

**Comment by stewartoallen** [comment]
can you attach a workspace (.kmz) that I can use to replicate? keeping the same workspace and switching between 4.0 and 3.9 produces very different gcode?

**Comment by goldenninja13** [comment]
It's not allowing me to attach a (.kmz) file type in github

**Comment by stewartoallen** [comment]
please email to [ sa at grid dot space ] or DM me on Discord. thanks

**Comment by stewartoallen** [comment]
this looks like a rendering bug in Preview mode. in the example you provided, the rendered paths are showing up as *very* slow, while the actual gcode does not match. when I re-import the generated GCode, it's a totally different picture showing more normal extrusion rates. this particular print shows a 4.5 hour print time.

<img width="869" alt="Screenshot 2024-07-12 at 3 48 32 PM" src="https://github.com/user-attachments/assets/7896d354-f51c-4d7c-a14c-a8304d9a4a74">

<img width="872" alt="Screenshot 2024-07-12 at 3 49 24 PM" src="https://github.com/user-attachments/assets/20ae803f-956e-4790-85bb-bb4c1ce776df">

**Comment by stewartoallen** [comment]
this is a good torture test. I'll use it to figure out what's going on and report back here.

**Comment by goldenninja13** [comment]
Thank you. The thing I don't understand with it is it will run like normal
for a little bit but then it will change and move so slow it doesn't even
look like it's moving. So I would have to think that somewhere when
outputting the gcodes it is not sending the right values. The print I sent
you was printing like normal for the first 30 minutes and it did seem like
it was only going to take 4-5 hours but then it slowed down and has now
been printing for 80h and is only 55% complete.

**Comment by stewartoallen** [comment]
aha. your output speeds are all 0, which leads to undefined behavior.

<img width="181" alt="Screenshot 2024-07-12 at 5 26 59 PM" src="https://github.com/user-attachments/assets/05085bea-a286-4eed-9290-38d3ce41a71d">

when I put in more sensible settings, things turn out better. I would also recommend using `linear`, `triangle`, or `grid` infill. Gyroid isn't helping here and takes tons more memory.

<img width="1108" alt="Screenshot 2024-07-12 at 5 29 58 PM" src="https://github.com/user-attachments/assets/e6760b83-7da7-49b2-9990-51e6bd068598">

**Comment by stewartoallen** [comment]
there is one remaining issue which is the model reports as 'non-manifold' which leads to a solid layer in the middle of the otherwise hollow sphere (it's in the trench area). i'll see if there is anything I can do to work around that, but fixing the model would be helpful.

**Comment by goldenninja13** [comment]
I figured that was probably an issue but I did print this model before the
update and it printed completely hollow.

**Comment by stewartoallen** [comment]
I've added a fix for the non-manifold slicing that will be in 4.0.6

**Comment by goldenninja13** [comment]
Thanks for the help
