### ISSUE TITLE
Will not slice CNC for ShapeOKO XXL

### ISSUE THREAD

**Issue by Neanderthal50** [GridSpace/grid-apps#284]
ver 4.0.16 worked well, 4.0.17 hangs at halfway progress.  Tried older Onshape files that worked before, same hang issue.  Cleared cache, no change.

**Comment by stewartoallen** [comment]
Is this happening in Onshape or on Grid.Space? Is there a workspace you can share with me? I'm testing KM in Onshape now with 4.0.17 and can't reproduce. Thanks

**Comment by Neanderthal50** [comment]
https://cad.onshape.com/documents/440b88aa532adc89737b5c21/w/ace64bd26ae4d217627b8992/e/b6e6a0cbaf312a653fa45721?renderMode=0&uiState=66ad5c43b58fb301b8545b8b

**Comment by Neanderthal50** [comment]
Appears to be the drill process.

**Comment by stewartoallen** [comment]
Thanks. I'm able to slice these parts in FDM and CNC modes. Can you look on the Javascript console for errors produce during slicing? Or use KM's Files -> Export menu to produce a `.kmz` file that I can use to replicate your exact setup.

<img width="1096" alt="Screenshot 2024-08-02 at 6 27 17 PM" src="https://github.com/user-attachments/assets/52c231b5-a472-467e-a4c6-69f3dfa12622">

<img width="850" alt="Screenshot 2024-08-02 at 6 26 58 PM" src="https://github.com/user-attachments/assets/ef704eb8-30db-4118-bc1a-8443e63ac6b3">

**Comment by stewartoallen** [comment]
found it. thanks. will push a fix to production in a couple of hours.

**Comment by Neanderthal50** [comment]
[workspace_V1.zip](https://github.com/user-attachments/files/16475882/workspace_V1.zip)

In the source drawing we set the holes to 7/32 in.  I have a tool set to 0.21875 in KiriMoto.  Is there another method to set auto hole sizing/drilling/match?

**Comment by Neanderthal50** [comment]
Awesome!  Thank you.  We'll continue building FRC robots at that time.  LOL

**Comment by stewartoallen** [comment]
there is a "marking" option that will mark all circular holes. but I have a TODO item to allow manual selection of holes similar to the way pocket and trace work.

**Comment by stewartoallen** [comment]
fix pushed. shift + reload and test. if in onshape, caching of iframes is trickier and may take some time to propagate.
