### ISSUE TITLE
[FR] duplicate tool

### ISSUE THREAD

**Issue by tcurdt** [GridSpace/grid-apps#287]
Right now you have to create tools from scratch. Often it just needs a slightly different diameter.
I would be convenient to add a "duplicate" button.

![Screenshot 2024-08-10 at 22 34 52](https://github.com/user-attachments/assets/04a264de-6b3d-4b6e-a9f7-d6c579f94d9e)

**Comment by stewartoallen** [comment]
auto-increments the tool id, adds 'copy' to name, and clones all other values

<img width="578" alt="Screenshot 2024-08-12 at 8 43 22 AM" src="https://github.com/user-attachments/assets/11e3059d-8c35-434d-b580-438530e7598a">
