### ISSUE TITLE
[FR] allow to name operations

### ISSUE THREAD

**Issue by tcurdt** [GridSpace/grid-apps#289]
I would be nice if one could give operations an (optional) name. Just to make it a little easier to make sense of the operations list.
![Screenshot 2024-08-10 at 22 43 38](https://github.com/user-attachments/assets/f5cf52f1-b7d9-466b-9be8-f4cb2fe9c2db)

**Comment by stewartoallen** [comment]
already possible. click the note pillow above the operation parameters to change the text. first #word becomes the new operation name.

<img width="356" alt="Screenshot 2024-08-10 at 8 04 44 PM" src="https://github.com/user-attachments/assets/a1a18e2f-20f3-48e5-8a41-86428b0b7de5">

<img width="352" alt="Screenshot 2024-08-10 at 8 05 08 PM" src="https://github.com/user-attachments/assets/0c7af8a5-09da-4d80-85cc-502dd1de12fb">
