### ISSUE TITLE
1/8" ball end cutter looks to large

### ISSUE THREAD

**Issue by dshier65** [GridSpace/grid-apps#305]
on CNC mode the cutter appears too large.   
![image](https://github.com/user-attachments/assets/a49cf7d1-19eb-46d4-82bd-0e2a9de1fc78)

**Comment by stewartoallen** [comment]
can you share a screenshot of your tool definition?

**Comment by dshier65** [comment]
I did add a screenshot.  Is it not showing up?  I will do another one when
I get back to the computer
Dan

**Comment by dshier65** [comment]
Yes tool definition I will add that

**Comment by dshier65** [comment]
is this what you are looking for?
[image: image.png]

**Comment by dshier65** [comment]
is this what you are looking for>
![image](https://github.com/user-attachments/assets/1e580e95-063e-4861-a4c7-51f5e2b65ea3)

**Comment by stewartoallen** [comment]
yes. you need to either check the `metric` box so `3.175` is interpreted as `mm` *or* change `3.175` to `0.125` which is the size in inches

**Comment by dshier65** [comment]
Ok, thanks for the clarification.
