### ISSUE TITLE
Laser cutter slicer fails on OnShape integration

### ISSUE THREAD

**Issue by xxv** [GridSpace/grid-apps#32]
I'm not sure how to make a reproducible example that I can send, but the laser cutter slicer doesn't seem to work when I import from OnShape. If I export them as STL from OnShape and then bring them to https://grid.space/kiri everything seems to work fine.

When I click on "Slice" it generates no results. When I click "preview" it keeps re-slicing it until I hit escape.

**Comment by xxv** [comment]
https://cad.onshape.com/documents/aa416eeae7b8d0745c26f54a/w/dd5943cad0143c55fc7bb0fb/e/d5049b87736bf3217981b76b Here's a sample document that seems to trigger this behavior.

**Comment by stewartoallen** [comment]
odd.  working for me.  what's your OS / Browser?  and what are the settings on the right panel?  send a screenshot, if you don't mind.

**Comment by xxv** [comment]
I just tried it on Firefox 57.0 on Debian Buster/sid and noticed it in Chrome Version 63.0.3239.30 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit). 

Here's the right panel: https://xxv.so/0xc7898754.png

**Comment by xxv** [comment]
When I click on Laser Cutter -> Slice I get:
![0x426d244e](https://user-images.githubusercontent.com/124381/38817253-f8c2dd12-4165-11e8-812e-c512b14444c7.png)

Then when I click on "Preview" I get:

![0x0f37ab92](https://user-images.githubusercontent.com/124381/38817285-0ac24480-4166-11e8-9260-bda60e5ab5ff.png)

And it never finishes.

**Comment by stewartoallen** [comment]
anything on the javascript console?

**Comment by xxv** [comment]
Hm. It looks like it's probably some sort of race condition. I'm getting successful slicing sometimes and not others. I didn't see any errors on the console last I checked, but I'll keep playing with it to see if I can reproduce the issue with console logging on.
