### ISSUE TITLE
Tool change turns off spindle

### ISSUE THREAD

**Issue by jwhite66** [GridSpace/grid-apps#34]
On our old LinuxCNC Fireball, when it processes the M6 T1 tool change command, the spindle stops.  We need to either remove the M6 T1 or add a M3 Snnnn after the M6 to get back up to speed.  It seems like adding the M3 Snnnn would be correct.

**Comment by stewartoallen** [comment]
You can edit the tool change macro for your machine and add that line.  Clone and edit with the + in the lower left of the device dialog.

**Comment by jwhite66** [comment]
Sure enough.  That works for our purposes; I could see that someone else might like to be able to substitute in S{speed}, which does not appear to work.
