### ISSUE TITLE
Be able to send to OctoPrint via HTTP from Onshape

### ISSUE THREAD

**Issue by probonopd** [GridSpace/grid-apps#40]
My [OctoPrint-compatible host software](https://github.com/probonopd/WirelessPrinting) currently runs only HTTP and I seem to be unable to send GCODE there:

![printdirect](https://user-images.githubusercontent.com/2480569/43370148-3fe067b2-937a-11e8-8b51-98f94cb3328e.PNG)

Please allow sending to HTTP hosts from within Onshape.

**Comment by stewartoallen** [comment]
Sorry about that.  In order to run inside Onshape, grid.space must be entirely https.  And https sites can't access non-secure content.  You can run Kiri:moto locally on the same host that runs your octo-print server.

**Comment by probonopd** [comment]
Is there some other way to send a HTTP request from JavaScript? I mean, it's just a simple POST request...

**Comment by stewartoallen** [comment]
The integration does use a simple http post using javascript.  It's a standard browser security restriction to disallow https -> http.

**Comment by probonopd** [comment]
I see. Thanks for your explanation.

**Comment by probonopd** [comment]
Do you think it could be made work with something like the `--allow-running-insecure-content` command line option? I am asking in part since a dedicated, pre-configured Electron application for Onshape like https://github.com/develar/onshape-desktop-shell/ might be able to relax some security settings if this helps.

**Comment by probonopd** [comment]
Another option might be to open a HTTP popup window, and send the CGODE from there.

https://stackoverflow.com/a/44943661

**Comment by stewartoallen** [comment]
That won't work without sending the entire gcode server-side then bouncing it back to the new window.  Doable, but not elegant, easy, or contained.  Kiri does not send any data to the server at present, so that would be a huge departure.

**Comment by stewartoallen** [comment]
closing as not feasible unless octoprint implements https with real certs
