### ISSUE TITLE
Holes on top of prints

### ISSUE THREAD

**Issue by probonopd** [GridSpace/grid-apps#43]
Speed when printing the first top layer above an area of infill is too high, causing holes when a 10% infill pattern is used.

The first layer in top of an area of infill should be printed at reduced speed (I think to allow for better cooling and hence better "bridging" the infill). Looks like other slicers print the first layer above infill at a speed that can be set separately, e.g., I think this is what `top_solid_infill_speed` does in Slic3r.

@luotinen did a test at https://github.com/daid/LegacyCura/issues/771#issuecomment-114188028:

![](https://cloud.githubusercontent.com/assets/6695329/8288002/17f3af42-191c-11e5-8f99-ed5488956342.jpg)

**Comment by filipgoc** [comment]
(for random people reading this, probonopd probably knows)

This issue actually looks like 'pillowing' - which is cause by a combination of too thin a top (use more layers) and insufficient cooling. Lower your print temp and/or add another cooling fan.

**Comment by stewartoallen** [comment]
and/or increase top layers
