### ISSUE TITLE
Gyroid Infill

### ISSUE THREAD

**Issue by probonopd** [GridSpace/grid-apps#44]
Gyroid Infill has been shown to provide great strength at low material consumption, print time, and printer wear. Recent versions of Slic3r support it. It would be a great addition to Kiri:Moto and possibly should even be the default.

![gyroid](https://user-images.githubusercontent.com/2480569/43411915-e1708650-942b-11e8-991b-fb8da391b6c9.jpeg)

https://mattshub.com/2018/03/15/gyroid-infill/

**Comment by stewartoallen** [comment]
completed a while back. forgot to close this.
