### ISSUE TITLE
Discover OctoPrint instances using mDNS/Zeroconf

### ISSUE THREAD

**Issue by probonopd** [GridSpace/grid-apps#45]
OctoPrint advertises itself in the network as the `octoprint` zeroconf service. 
At least on Chrome, one should be able to find the OctoPrint instances running on the local network using https://developer.chrome.com/apps/mdns, hence offering a list of available OctoPrint instances to the user rather than having them type the IP address.

http://docs.octoprint.org/en/master/bundledplugins/discovery.html#zeroconf-service-octoprint-tcp

**Comment by stewartoallen** [comment]
that would be a welcome diff

**Comment by probonopd** [comment]
If only I had some JavaScript experience. Looks like it is not _that_ hard _if_ you know what you are doing ;-)

**Comment by stewartoallen** [comment]
True of most of your requests.  My gating factor now is time.  I'm 100% on another project through summer, at a minimum.

**Comment by probonopd** [comment]
Thanks for doing this project. It's awesome. CAD and slicing out to be integrated with each other.

**Comment by stewartoallen** [comment]
Thanks.  A lot has gone into it.  I'll get back to it in time.

**Comment by stewartoallen** [comment]
the chrome.mdns api does not appear in any of my version of chrome (up to date)

**Comment by probonopd** [comment]
Indeed, a quick web search did not turn up something that is really working. It's really a shame that Apple seem to be the only ones who care about Zeroconf. It's such a marvel of "it just works" technology 👍

**Comment by stewartoallen** [comment]
Use the new [OctoPrint-GridSpace](https://github.com/GridSpace/OctoPrint-GridSpace) plugin for OctoPrint to achieve zero-config print sending
