### ISSUE TITLE
Right-hand side settings in printer profiles

### ISSUE THREAD

**Issue by probonopd** [GridSpace/grid-apps#46]
Would it be possible to pre-configure the right-hand side settings in printer profiles? I think some of the right-hand side defaults are not ideal for my printer, and hence would like to provide a more suitable set of settings as part of the printer profile.

![](https://user-images.githubusercontent.com/2480569/43421536-52782306-9447-11e8-9b12-d509c53295de.png)

**Comment by stewartoallen** [comment]
perhaps [this](https://github.com/GridSpace/grid-apps/wiki/Profile-Persistence) addresses your issue.  otherwise, use load/save to group settings that are effective for your printer.
