### ISSUE TITLE
CNC Mill, Small Counter Bore does not cut to bottom of model

### ISSUE THREAD

**Issue by RLute** [GridSpace/grid-apps#55]
When cutting Small diameter counter bores <16mm diameter, the slicer does not cut to the bottom of the bore. 

15, 10 and 6 mm bores do not cut to the bottom of the shoulder in the model. 

![6mm 10mm 15mm c bore](https://user-images.githubusercontent.com/46653285/51088630-fef6ce00-172f-11e9-9e3f-8d041b883702.jpg)

16 mm and 10 mm bores cut to the bottom, but the small 6mm dia bore does not cut to the bottom of the model

![6mm 10mm 16mm c bore](https://user-images.githubusercontent.com/46653285/51088633-08803600-1730-11e9-82af-5f4318adb8c8.jpg)

I would upload the .STL files but it won't let me.
If I am doing something wrong please feel free to let me know how to correct it.

**Comment by stewartoallen** [comment]
please email the stl to me: sa@grid.space

**Comment by stewartoallen** [comment]
fixed in v2.3 & v2.4 releases. if you are still having trouble, please provide a workspace export (.km file).
