### ISSUE TITLE
App loading fails / Variable t declared twice

### ISSUE THREAD

**Issue by rqhub** [GridSpace/grid-apps#56]
Using OSX / Safari 10.1.1
Javascript fails / Page almost blank
Error seen in console: 

[Error] SyntaxError: Cannot declare a let variable twice: 't'.
	(fonction anonyme) (1.2.6e:3)

which points here (line 1937)
 Kt.Clipper.prototype.ProcessEdgesAtTopOfScanbeam = function(t) {

**Comment by stewartoallen** [comment]
That version of safari is very old. Have you tried a newer version?

**Comment by rqhub** [comment]
i've running the app locally , via github, That works.
