### ISSUE TITLE
Lathe CNC toolpaths

### ISSUE THREAD

**Issue by korpx** [GridSpace/grid-apps#58]
Any plans on ability to generate lathe cnc toolpaths?
That would fill a void in the opensource / freely available segment.

**Comment by stewartoallen** [comment]
It's not something I've considered before.  There are more constraints on lathe objects than the other three supported modes.  I expect it would take a few weeks of solid work to get it right.  I don't anticipate having that kind of time in the near term.

**Comment by stewartoallen** [comment]
added to the todo list and closing for now.
