### ISSUE TITLE
Origin ???

### ISSUE THREAD

**Issue by rqhub** [GridSpace/grid-apps#59]
Hi
In CNC mode
in previous versions the origin used to be the edge of the stl object bounding box

In the current version, the 0,0 point is something different than the 0,0 of the STL bounding box (and i couldn't guess what exactly, it's not the diameter, it's not half the diameter)

Not knowing where the 0,0 reference makes it extremely tedious to use (after wrecking 3 parts, i gave up).

**Comment by stewartoallen** [comment]
Nothing should have changed regarding origins

**Comment by rqhub** [comment]
Maybe i just noticed now then?
Remind me the rule, 0,0 is the lower left edge of the bounding box?

**Comment by rqhub** [comment]
Solved. Hidden config in CNC controller. My bad.
