### ISSUE TITLE
"; --- layer {n}" comments are not added when using custom devices

### ISSUE THREAD

**Issue by filipgoc** [GridSpace/grid-apps#61]
I'm in the FDM mode. 

![image](https://user-images.githubusercontent.com/16858474/55167576-8d94bc00-5171-11e9-91d4-00a59e22b4dd.png)

If using one of the included Devices,
`; --- layer " + layer + " (" + consts.height + " @ " + consts.z + ") ---` is added as planned. 

When I use a custom device (created in the UI by clicking the plus button on the lower left and creating a copy of an existing one), there are no layer comments in the resulting gcode. 

I think this is a bug. 

---

I thought about adding the comment it as a layer script, but then I don't see how I could add the layer number there.

**Comment by stewartoallen** [comment]
a post-processor strips comments in custom mode because some printers fail when they are present. I had meant to make that a checkbox configuration option, but haven't got around to it.

**Comment by filipgoc** [comment]
Got it. So it's a _feature_, not a bug. 👍
