### ISSUE TITLE
Raft and Support Interface

### ISSUE THREAD

**Issue by dugbraden** [GridSpace/grid-apps#64]
When using a raft in conjunction with support, support does not extend down to the surface of the bed. Support begins at the level of the raft, which means it prints about 2mm off the print bed.

Example with a simple object:

![2019-04-17 11_02_48](https://user-images.githubusercontent.com/36244464/56301344-a0156c00-6105-11e9-8882-e345e0f2f468.png)

Now with Slice selected:

![2019-04-17 11_02_58](https://user-images.githubusercontent.com/36244464/56301389-b9b6b380-6105-11e9-91e3-5fba7bf9f2a1.png)

Note that the support is flush on the print bed. When Preview is selected:

![2019-04-17 11_03_04](https://user-images.githubusercontent.com/36244464/56301425-c63b0c00-6105-11e9-8e40-fc75956d9078.png)

You can see the gap between the surface and the support. I have verified this with a few prints, the stl in question was just to clearly show what is going on.

This is the same across printer models. It may be a corner case, but printing objects created by students often requires rafts in conjunction with support, especially when using an unheated bed.

**Comment by stewartoallen** [comment]
Good catch.  The raft should, in theory, extend under the entire part, including the overhang.

**Comment by dugbraden** [comment]
Hi,

In the early days of Simplify 3D (before they enabled a continuous first layer in support) I would insert tiny flat objects in the base support area, to give the single line support material a solid surface to grab on to. I've tried (with middling success) to get students and teachers to do the same here.

Not sure how intractable this problem is, or if I can help in any way. Please let me know!

Doug

**Comment by stewartoallen** [comment]
fixed in latest commit

https://github.com/GridSpace/grid-apps/commit/55bc45928540fbaf9ddbdef9171088aa273f0b51
