### ISSUE TITLE
Laser and CAM in OnShape aren't "Slicing"

### ISSUE THREAD

**Issue by brakthehun** [GridSpace/grid-apps#66]
![2019-08-27 13_54_22-](https://user-images.githubusercontent.com/16564592/63807288-405c7800-c8d2-11e9-83cc-b27f3c5df2ae.png)

It won't work no matter what part I try.

**Comment by brakthehun** [comment]
![2019-10-26 00_01_20-Window](https://user-images.githubusercontent.com/16564592/67616071-2c75ab00-f789-11e9-81ea-8fc3fc8d5a07.png)
It was working yesterday and now it isn't.

**Comment by stewartoallen** [comment]
on the right hand side, are any process selected or are all the checkboxes empty?  a full screenshot would be more helpful.

**Comment by stewartoallen** [comment]
please email the STL to me at sa@grid.space and I will try to replicate. thanks

**Comment by brakthehun** [comment]
https://cad.onshape.com/documents/d13d6fb9fe70d757edefc61d/w/ba34f76b6e2812ea6a5df67e/e/b54aed74949e01c706e0a36c

**Comment by brakthehun** [comment]
It seems that importing STL in to grid space works,, but going directly from OnShape is having intermittent issues.

**Comment by stewartoallen** [comment]
please re-open if this has not been resolved.
