### ISSUE TITLE
Cut out tabs fail to consistently generate

### ISSUE THREAD

**Issue by activexposure** [GridSpace/grid-apps#7]
I'm working in Onshape and using Kiri:moto to generate my g-code.
Kirimoto seems to fail to generate cutout tabs for narrow parts and with the drill operation defaulting to  be the last step I'm unable to successfully finish cutting my parts with my CNC machine.
When Kiri:moto does generate cutout tabs the tool size hasn't been accounted for in the operation and the final lines of code cut through the tabs.
I've attached a screenshot of the preview which shows the cutout generated but subsequently cut away.
Any solves for this out there?
![screen shot 2017-10-04 at 5 44 28 pm](https://user-images.githubusercontent.com/32504377/31160269-b8bf11cc-a92b-11e7-8748-1d04276ec170.png)

**Comment by stewartoallen** [comment]
I do not have a workaround for this other than machining each part individually

**Comment by stewartoallen** [comment]
can you share this model with me (sa@grid.space) ?  I'm not able to replicate this with similar models on my side.  thanks

**Comment by Harvie** [comment]
Sometimes the cutout tab errors are quite strange and irregular:

![image](https://user-images.githubusercontent.com/276504/36941119-d33cd54a-1f53-11e8-932a-e6616e52673f.png)

Other times quite regular:

![image](https://user-images.githubusercontent.com/276504/36941084-44e5a51a-1f53-11e8-975a-f74029090b2e.png)

**Comment by stewartoallen** [comment]
it attempts to place them top, bottom, left and right center.  it's a difficult algorithm.  try rotating the model a few degrees.

**Comment by stewartoallen** [comment]
tabs have been recoded in recent releases. please review.
