### ISSUE TITLE
When arranging parts, <alt> left and <alt> right work, but <alt> up and <alt> down do nothing

### ISSUE THREAD

**Issue by JoseBaer** [GridSpace/grid-apps#70]

**Comment by stewartoallen** [comment]
what is your browser and OS?

**Comment by JoseBaer** [comment]
Chrome on a Chromebook

**Comment by stewartoallen** [comment]
can you see if the window manager is reserving alt-arrow up/down.  it's working in Chrome (and Firefox and Safari) on other OSs.  unfortunately, I don't have a Chromebook for testing.

**Comment by JoseBaer** [comment]
I can also get it to work on other platforms. I haven't been able to figure
out whether the window manager is reserving those keys. There doesn't
appear to be any chromebook specific shortcuts for alt-arrow up/down.

Jose



José Baer

Oso Ag LLC

www.OsoAg.com
(805) 705-4707

<http://www.osoag.com>

**Comment by stewartoallen** [comment]
thanks for the follow-up.  is this critical functionality for you?  i use kiri every day (for years) and forgot that feature was even in there.  this is a chromebook issue i likely can't work around.

**Comment by JoseBaer** [comment]
[image: image.png]
It looks as if alt-arrow up/down are reserved for Page up and Page down in
a Chromebook.

Jose



José Baer

Oso Ag LLC

www.OsoAg.com
(805) 705-4707

<http://www.osoag.com>

**Comment by JoseBaer** [comment]
I have to switch to a windows machine to arrange my parts on a sheet of
plywood for the router. If Kiri-Moto would default to the same layout of
parts as I have in my part studio, then I would not have to do anything. Is
there some way I can make Kiri-Moto do a default layout that matches the
one in my parts studio?

Jose



José Baer

Oso Ag LLC

www.OsoAg.com
(805) 705-4707

<http://www.osoag.com>

**Comment by stewartoallen** [comment]
Yes, there is a way to do this. When importing, switch to FDM Printing mode then click on the part studio instead of an individual item to bring in all the items. After importing, switch back to CAM mode. I will change the behavior so that this works in CAM mode, too, in the future.

**Comment by JoseBaer** [comment]
Thank you! That is really helpful.

Jose



José Baer

Oso Ag LLC

www.OsoAg.com
(805) 705-4707

<http://www.osoag.com>

**Comment by stewartoallen** [comment]
can we consider this closed?

**Comment by JoseBaer** [comment]
Yes

**Comment by stewartoallen** [comment]
thanks!
