### ISSUE TITLE
Update Broke CNC Cutout Tab Pathing with multiple Objects

### ISSUE THREAD

**Issue by mp2chan** [GridSpace/grid-apps#72]
With the new update, cuttout tabs with multiple object create improper heights for tab cutting.  As demonstrated in the image attached, teh tab path instead of rising to the correct safe distance, it's only rising to the height of the second layer and 'cutting' right through to the next tab spot. 

![image](https://user-images.githubusercontent.com/2230595/77268221-dbe87800-6c6a-11ea-9fab-4b218fc1aeaf.png)

This consistently happens when there's more than one object in the layout, if an object is alone the paths are as they were prior to the update

**Comment by stewartoallen** [comment]
Please include a screenshot of your settings or share your profile settings [this way](https://github.com/GridSpace/grid-apps/wiki/Profile-Persistence).  Which version is this?  1.7.7?  Can you include the STL?  thanks

**Comment by stewartoallen** [comment]
I was able to replicate this by disabling "depth first" and with a roughing pass only.  For now, please try enabling "depth first" and see if that works.  I'll fix this in the next update.  thanks

**Comment by stewartoallen** [comment]
I was able to replicate this. Fixing now.

**Comment by stewartoallen** [comment]
from the looks of it, this has been a bug for a **_long time_** and just went unnoticed.  fix will be live on grid.space in an hour or two.

**Comment by mp2chan** [comment]
Pathing is all good now!

Thanks!
