### ISSUE TITLE
cnc milling curves only doesnt work

### ISSUE THREAD

**Issue by fxrnando** [GridSpace/grid-apps#73]
As the title says. I've tryed a lot of configurations but on finishing, "x" "y" "curves only" checked, it still generate path from side to side of the element.

**Comment by stewartoallen** [comment]
Looks like a recent update broke that. Will fix shortly.

**Comment by stewartoallen** [comment]
v1.7.9 pushed to production with a potential fix.  please let me know.  thanks

**Comment by fxrnando** [comment]
I created a model with the new fix. Everything is working great so far. Thanks.

**Comment by stewartoallen** [comment]
great. please re-open if you find another bug.
