### ISSUE TITLE
CNC - No Tool Based Spindle Speed or Feed Rate

### ISSUE THREAD

**Issue by kingofl337** [GridSpace/grid-apps#83]
Would you be willing to add tool based spindle speed and feed rate for CNC Milling Machines? As the diameter of the Endmill or Material Changes the Feed Rate and Spindle speed needs to change.

Also, is there a submission method for machines on your list?

**Comment by stewartoallen** [comment]
it should exist already. it looks like a new bug is hiding that feature. will post a fix shortly.

**Comment by stewartoallen** [comment]
please confirm this is fixed for you and close the ticket.
