### ISSUE TITLE
First layer settings

### ISSUE THREAD

**Issue by varazir** [GridSpace/grid-apps#85]
Hello 

I found this slicer today and it looks good, just that I need the temp to be >220C ( allmetal hotend).
Have set that in the output value but when I check the gocde the first layer is hard coded to 200C and I can't find any where to change that.

**Comment by stewartoallen** [comment]
enabling expert mode will give you a lot more parameters

![Screen Shot 2020-07-06 at 12 49 47 PM](https://user-images.githubusercontent.com/554275/86618632-4063e480-bf87-11ea-80e3-8be3d5665290.png)

![Screen Shot 2020-07-06 at 12 49 56 PM](https://user-images.githubusercontent.com/554275/86618646-43f76b80-bf87-11ea-815b-3252b21471e8.png)
