### ISSUE TITLE
Getting "no process selected"

### ISSUE THREAD

**Issue by kolchagov** [GridSpace/grid-apps#86]
With version 2.2.0 (latest update)
using CAM I've got error "no process selected". Also the tools don't appear in drop-down list and cannot be selected

I've tried this on both Chrome (latest) and Firefox 77

Steps to reproduce:

-  open kiri moto page    
- select mode as "cnc milling"
- select any machine
- try to enable process - e.g. "rough" - tools dropdown is empty
- click 'slice' (i.e. leave everything else as defaults)

**Comment by stewartoallen** [comment]
I see this, too. Thanks for the report. There seems to have been a stale caching issue on the server. I wiped the cache and restarted the server and it seems to be working now. Please confirm and close this if fixed.
