### ISSUE TITLE
Is there a function to reset/clear the workspace without reloading?

### ISSUE THREAD

**Issue by juodumas** [GridSpace/grid-apps#88]
I am using Kiri:Moto with onshape for laser cutting. The only way to import a new set of parts that I could find is to delete all parts by hand (which is cumberson with >6 parts) or to reload the page (it's slow). It would be nice to have a function to delete all parts before importing. Maybe 'R' shortcut with a confirmation prompt?

**Comment by stewartoallen** [comment]
ctrl + a on windows and cmd + a on mac should select all parts. then the [delete] key should remove all selected parts.

**Comment by juodumas** [comment]
Hm, not working for me at https://grid.space/kiri/ or from within onshape. I click view->arrange, ctrl-a and nothing happens. Version `3.0.0-dev`.

**Comment by stewartoallen** [comment]
windows? possible you have caps lock on? sometimes the onshape iframe prevents keyboard focus.

**Comment by juodumas** [comment]
Thanks!
