### ISSUE TITLE
STL import into Kiri:Moto doesn't observe user's inch/mm preference

### ISSUE THREAD

**Issue by foxharp** [GridSpace/grid-apps#98]
STL files are unitless, so the exporter and importer need to agree -- no conversion can be done automatically.  When I export STL from Onshape, I get a choice of units.  I initially chose inches, since that's how I use KM.    But KM seems to import with the assumption of mm, regardless of its preference setting.

The workaround is (obviously) to always choose mm when exporting from Onshape.

**Comment by stewartoallen** [comment]
True. When KM is inside Onshape, the transfer happens behind the scenes using mm. I will update the STL drop loader to respect workspace units.

**Comment by stewartoallen** [comment]
fixed in git. will push to production with the next release.
